@Store.Api_HostAddress = http://localhost:5009

### Listar produtos
GET {{Store.Api_HostAddress}}/api/v1/products
Accept: application/json

### Criar produto
POST {{Store.Api_HostAddress}}/api/v1/products
Content-Type: application/json

{
  "name": "Teclado",
  "price": 249.90
}

### Buscar produto por id
GET {{Store.Api_HostAddress}}/api/v1/products/1
Accept: application/json

### Atualizar produto
PUT {{Store.Api_HostAddress}}/api/v1/products/1
Content-Type: application/json

{
  "name": "Teclado mecânico",
  "price": 349.90
}

### Excluir produto
DELETE {{Store.Api_HostAddress}}/api/v1/products/1
